apiVersion: v1
kind: Pod
metadata:
  name: init
spec:
  containers:
  - name: debug
    image: alpine:3.12
    command: ["sleep","3600"]
    volumeMounts:
    - name: data
      mountPath: /web
  volumes:
  - name: data
    hostPath:
      path: /tmp
