apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app3: web
spec:
  containers:
  - name: web
    image: nginx:1.17-alpine
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data
    hostPath:
      path: /tmp
