apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app3: web
  template:
    metadata:
      labels:
        app3: web
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine
